steps:
# install Test requirements
- name: "docker.io/library/python:3.8"
  args: ['pip', 'install', '-t', '/workspace/lib', '-r', 'requirements.txt']

- name: 'docker.io/library/python:3.8'
  args: ["python", "tests/main.py"]
  env: ["PYTHONPATH=/workspace/lib"]

# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA', '.']
  
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA']
  
# deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'instapuller-${_DEPLOY_ENVIRONMENT}', 
    '--image', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA', 
    '--region', '${_RUN_REGION}',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--quiet'
    ]

substitutions:
  _DEPLOY_ENVIRONMENT: 'staging'
  _RUN_REGION: 'us-central1'