steps:
  # install Test requirements
# - name: "docker.io/library/python:3.8"
#   args: ['pip', 'install', '-t', '/workspace/lib', '-r', 'requirements.txt']

# TODO: Make tests work again
# - name: 'docker.io/library/python:3.8'
#   args: ["python", "tests/main.py"]
#   env: ["PYTHONPATH=/workspace/lib"]

#   # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA', '.']
  
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA']
  
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'alpha', 'run', 'deploy', 'instapuller-preview', 
    '--image', 'gcr.io/$PROJECT_ID/instapuller:$SHORT_SHA', 
    '--region', '${_RUN_REGION}',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--tag=preview-$SHORT_SHA',
    '--no-traffic',
    '--quiet'
    ]

# add preview URL as a comment on Pull Request    
- name: bash
  args:
    - '-c' # execute the following in a bash shell
    - |-
      /bin/pr_comment_post.sh \
      $_GH_USERNAME/instapuller \
      $_PR_NUMBER \
      "Preview this revision: FOO"
  secretEnv:
    - GITHUB_TOKEN
    
substitutions:
  _RUN_REGION: 'us-central1'
  _GH_USERNAME: 'davidstanke'

secrets:
  - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/instapuller/cryptoKeys/github-token
    secretEnv: 
      GITHUB_TOKEN: $_GITHUB_TOKEN